"""WAF fingerprinting — detect Cloudflare, AWS WAF, ModSecurity, Sucuri, Wordfence."""
from __future__ import annotations
import re
import asyncio
from dataclasses import dataclass, field

import httpx

_PROBE_PAYLOAD = "/?wp-hijack-waf-test=1'%20AND%20'1'='1"


@dataclass
class WAFResult:
    detected: bool = False
    name: str | None = None
    confidence: int = 0       # 0-100
    bypass_hints: list[str] = field(default_factory=list)
    signals: list[str] = field(default_factory=list)


# ── Signature DB ───────────────────────────────────────────────────────────────
_WAF_SIGNATURES: list[dict] = [
    {
        "name": "Cloudflare",
        "headers":  {"server": r"cloudflare", "cf-ray": r".+"},
        "body_res": [r"attention required.*cloudflare", r"cloudflare ray id"],
        "status_codes": {403, 429, 503},
        "bypass_hints": [
            "Try X-Forwarded-For: 127.0.0.1",
            "Try Host: internal.target.com",
            "Chunk payload with Transfer-Encoding: chunked",
        ],
    },
    {
        "name": "AWS WAF",
        "headers":  {"x-amzn-requestid": r".+", "x-amz-cf-id": r".+"},
        "body_res": [r"aws.+waf", r"not acceptable"],
        "status_codes": {403},
        "bypass_hints": [
            "Use double URL encoding: %%2527",
            "Mix case: SeLeCt instead of SELECT",
        ],
    },
    {
        "name": "ModSecurity",
        "headers":  {"server": r"mod_security"},
        "body_res": [r"not acceptable", r"modsecurity", r"406 not acceptable"],
        "status_codes": {406, 403},
        "bypass_hints": [
            "Use HPP (HTTP Parameter Pollution)",
            "Encode payloads in base64 with eval(atob(...))",
        ],
    },
    {
        "name": "Sucuri",
        "headers":  {"x-sucuri-id": r".+", "server": r"sucuri"},
        "body_res": [r"sucuri website firewall", r"access denied.*sucuri"],
        "status_codes": {403},
        "bypass_hints": [
            "Try direct-to-origin IP if resolvable",
            "Use X-Originating-IP: 127.0.0.1",
        ],
    },
    {
        "name": "Wordfence",
        "headers":  {},
        "body_res": [r"wordfence", r"generated by wordfence"],
        "status_codes": {403, 503},
        "bypass_hints": [
            "Slow-rate the requests (1 req/2s)",
            "Try obfuscated SQL keywords",
        ],
    },
]


def _check_signature(resp: httpx.Response, sig: dict) -> int:
    pts = 0
    # Header matching
    for hdr, pattern in sig.get("headers", {}).items():
        value = resp.headers.get(hdr, "")
        if re.search(pattern, value, re.I):
            pts += 25

    # Body matching
    for pattern in sig.get("body_res", []):
        try:
            if re.search(pattern, resp.text, re.I):
                pts += 20
        except Exception:
            pass

    # Status code
    if resp.status_code in sig.get("status_codes", set()):
        pts += 10

    return min(pts, 100)


async def detect_waf(http, base_url: str) -> WAFResult:
    result = WAFResult()
    probe_url = base_url.rstrip("/") + _PROBE_PAYLOAD

    try:
        resp = await http.get(probe_url, timeout=10)
    except Exception:
        return result

    best_score = 0
    best_sig: dict | None = None
    for sig in _WAF_SIGNATURES:
        score = _check_signature(resp, sig)
        if score > best_score:
            best_score = score
            best_sig = sig

    if best_sig and best_score >= 20:
        result.detected = True
        result.name = best_sig["name"]
        result.confidence = best_score
        result.bypass_hints = best_sig.get("bypass_hints", [])
        result.signals.append(f"Score {best_score}/100 matching {best_sig['name']} signatures")

    return result
